/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserLastState } from "./UserLastState";
import { UserLastStateCountArgs } from "./UserLastStateCountArgs";
import { UserLastStateFindManyArgs } from "./UserLastStateFindManyArgs";
import { UserLastStateFindUniqueArgs } from "./UserLastStateFindUniqueArgs";
import { DeleteUserLastStateArgs } from "./DeleteUserLastStateArgs";
import { UserLastStateService } from "../userLastState.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => UserLastState)
export class UserLastStateResolverBase {
  constructor(
    protected readonly service: UserLastStateService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "UserLastState",
    action: "read",
    possession: "any",
  })
  async _userLastStatesMeta(
    @graphql.Args() args: UserLastStateCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [UserLastState])
  @nestAccessControl.UseRoles({
    resource: "UserLastState",
    action: "read",
    possession: "any",
  })
  async userLastStates(
    @graphql.Args() args: UserLastStateFindManyArgs
  ): Promise<UserLastState[]> {
    return this.service.userLastStates(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => UserLastState, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UserLastState",
    action: "read",
    possession: "own",
  })
  async userLastState(
    @graphql.Args() args: UserLastStateFindUniqueArgs
  ): Promise<UserLastState | null> {
    const result = await this.service.userLastState(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UserLastState)
  @nestAccessControl.UseRoles({
    resource: "UserLastState",
    action: "delete",
    possession: "any",
  })
  async deleteUserLastState(
    @graphql.Args() args: DeleteUserLastStateArgs
  ): Promise<UserLastState | null> {
    try {
      return await this.service.deleteUserLastState(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
