/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserCoins } from "./UserCoins";
import { UserCoinsCountArgs } from "./UserCoinsCountArgs";
import { UserCoinsFindManyArgs } from "./UserCoinsFindManyArgs";
import { UserCoinsFindUniqueArgs } from "./UserCoinsFindUniqueArgs";
import { DeleteUserCoinsArgs } from "./DeleteUserCoinsArgs";
import { UserCoinsService } from "../userCoins.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => UserCoins)
export class UserCoinsResolverBase {
  constructor(
    protected readonly service: UserCoinsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "UserCoins",
    action: "read",
    possession: "any",
  })
  async _userCoinsItemsMeta(
    @graphql.Args() args: UserCoinsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [UserCoins])
  @nestAccessControl.UseRoles({
    resource: "UserCoins",
    action: "read",
    possession: "any",
  })
  async userCoinsItems(
    @graphql.Args() args: UserCoinsFindManyArgs
  ): Promise<UserCoins[]> {
    return this.service.userCoinsItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => UserCoins, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UserCoins",
    action: "read",
    possession: "own",
  })
  async userCoins(
    @graphql.Args() args: UserCoinsFindUniqueArgs
  ): Promise<UserCoins | null> {
    const result = await this.service.userCoins(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UserCoins)
  @nestAccessControl.UseRoles({
    resource: "UserCoins",
    action: "delete",
    possession: "any",
  })
  async deleteUserCoins(
    @graphql.Args() args: DeleteUserCoinsArgs
  ): Promise<UserCoins | null> {
    try {
      return await this.service.deleteUserCoins(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
