/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserHearts } from "./UserHearts";
import { UserHeartsCountArgs } from "./UserHeartsCountArgs";
import { UserHeartsFindManyArgs } from "./UserHeartsFindManyArgs";
import { UserHeartsFindUniqueArgs } from "./UserHeartsFindUniqueArgs";
import { DeleteUserHeartsArgs } from "./DeleteUserHeartsArgs";
import { UserHeartsService } from "../userHearts.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => UserHearts)
export class UserHeartsResolverBase {
  constructor(
    protected readonly service: UserHeartsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "UserHearts",
    action: "read",
    possession: "any",
  })
  async _userHeartsItemsMeta(
    @graphql.Args() args: UserHeartsCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [UserHearts])
  @nestAccessControl.UseRoles({
    resource: "UserHearts",
    action: "read",
    possession: "any",
  })
  async userHeartsItems(
    @graphql.Args() args: UserHeartsFindManyArgs
  ): Promise<UserHearts[]> {
    return this.service.userHeartsItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => UserHearts, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UserHearts",
    action: "read",
    possession: "own",
  })
  async userHearts(
    @graphql.Args() args: UserHeartsFindUniqueArgs
  ): Promise<UserHearts | null> {
    const result = await this.service.userHearts(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => UserHearts)
  @nestAccessControl.UseRoles({
    resource: "UserHearts",
    action: "delete",
    possession: "any",
  })
  async deleteUserHearts(
    @graphql.Args() args: DeleteUserHeartsArgs
  ): Promise<UserHearts | null> {
    try {
      return await this.service.deleteUserHearts(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
