/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { StateOfPurchases } from "./StateOfPurchases";
import { StateOfPurchasesCountArgs } from "./StateOfPurchasesCountArgs";
import { StateOfPurchasesFindManyArgs } from "./StateOfPurchasesFindManyArgs";
import { StateOfPurchasesFindUniqueArgs } from "./StateOfPurchasesFindUniqueArgs";
import { DeleteStateOfPurchasesArgs } from "./DeleteStateOfPurchasesArgs";
import { StateOfPurchasesService } from "../stateOfPurchases.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => StateOfPurchases)
export class StateOfPurchasesResolverBase {
  constructor(
    protected readonly service: StateOfPurchasesService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "StateOfPurchases",
    action: "read",
    possession: "any",
  })
  async _stateOfPurchasesItemsMeta(
    @graphql.Args() args: StateOfPurchasesCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [StateOfPurchases])
  @nestAccessControl.UseRoles({
    resource: "StateOfPurchases",
    action: "read",
    possession: "any",
  })
  async stateOfPurchasesItems(
    @graphql.Args() args: StateOfPurchasesFindManyArgs
  ): Promise<StateOfPurchases[]> {
    return this.service.stateOfPurchasesItems(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => StateOfPurchases, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "StateOfPurchases",
    action: "read",
    possession: "own",
  })
  async stateOfPurchases(
    @graphql.Args() args: StateOfPurchasesFindUniqueArgs
  ): Promise<StateOfPurchases | null> {
    const result = await this.service.stateOfPurchases(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => StateOfPurchases)
  @nestAccessControl.UseRoles({
    resource: "StateOfPurchases",
    action: "delete",
    possession: "any",
  })
  async deleteStateOfPurchases(
    @graphql.Args() args: DeleteStateOfPurchasesArgs
  ): Promise<StateOfPurchases | null> {
    try {
      return await this.service.deleteStateOfPurchases(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
