/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { StateOfPurchasesService } from "../stateOfPurchases.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { StateOfPurchasesCreateInput } from "./StateOfPurchasesCreateInput";
import { StateOfPurchases } from "./StateOfPurchases";
import { StateOfPurchasesFindManyArgs } from "./StateOfPurchasesFindManyArgs";
import { StateOfPurchasesWhereUniqueInput } from "./StateOfPurchasesWhereUniqueInput";
import { StateOfPurchasesUpdateInput } from "./StateOfPurchasesUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class StateOfPurchasesControllerBase {
  constructor(
    protected readonly service: StateOfPurchasesService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: StateOfPurchases })
  @nestAccessControl.UseRoles({
    resource: "StateOfPurchases",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createStateOfPurchases(
    @common.Body() data: StateOfPurchasesCreateInput
  ): Promise<StateOfPurchases> {
    return await this.service.createStateOfPurchases({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [StateOfPurchases] })
  @ApiNestedQuery(StateOfPurchasesFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "StateOfPurchases",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async stateOfPurchasesItems(
    @common.Req() request: Request
  ): Promise<StateOfPurchases[]> {
    const args = plainToClass(StateOfPurchasesFindManyArgs, request.query);
    return this.service.stateOfPurchasesItems({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: StateOfPurchases })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "StateOfPurchases",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async stateOfPurchases(
    @common.Param() params: StateOfPurchasesWhereUniqueInput
  ): Promise<StateOfPurchases | null> {
    const result = await this.service.stateOfPurchases({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: StateOfPurchases })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "StateOfPurchases",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateStateOfPurchases(
    @common.Param() params: StateOfPurchasesWhereUniqueInput,
    @common.Body() data: StateOfPurchasesUpdateInput
  ): Promise<StateOfPurchases | null> {
    try {
      return await this.service.updateStateOfPurchases({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: StateOfPurchases })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "StateOfPurchases",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteStateOfPurchases(
    @common.Param() params: StateOfPurchasesWhereUniqueInput
  ): Promise<StateOfPurchases | null> {
    try {
      return await this.service.deleteStateOfPurchases({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
