/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AccountBalance } from "./AccountBalance";
import { AccountBalanceCountArgs } from "./AccountBalanceCountArgs";
import { AccountBalanceFindManyArgs } from "./AccountBalanceFindManyArgs";
import { AccountBalanceFindUniqueArgs } from "./AccountBalanceFindUniqueArgs";
import { DeleteAccountBalanceArgs } from "./DeleteAccountBalanceArgs";
import { AccountBalanceService } from "../accountBalance.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => AccountBalance)
export class AccountBalanceResolverBase {
  constructor(
    protected readonly service: AccountBalanceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "AccountBalance",
    action: "read",
    possession: "any",
  })
  async _accountBalancesMeta(
    @graphql.Args() args: AccountBalanceCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [AccountBalance])
  @nestAccessControl.UseRoles({
    resource: "AccountBalance",
    action: "read",
    possession: "any",
  })
  async accountBalances(
    @graphql.Args() args: AccountBalanceFindManyArgs
  ): Promise<AccountBalance[]> {
    return this.service.accountBalances(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => AccountBalance, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "AccountBalance",
    action: "read",
    possession: "own",
  })
  async accountBalance(
    @graphql.Args() args: AccountBalanceFindUniqueArgs
  ): Promise<AccountBalance | null> {
    const result = await this.service.accountBalance(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => AccountBalance)
  @nestAccessControl.UseRoles({
    resource: "AccountBalance",
    action: "delete",
    possession: "any",
  })
  async deleteAccountBalance(
    @graphql.Args() args: DeleteAccountBalanceArgs
  ): Promise<AccountBalance | null> {
    try {
      return await this.service.deleteAccountBalance(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
