/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Roadmap } from "./Roadmap";
import { RoadmapCountArgs } from "./RoadmapCountArgs";
import { RoadmapFindManyArgs } from "./RoadmapFindManyArgs";
import { RoadmapFindUniqueArgs } from "./RoadmapFindUniqueArgs";
import { DeleteRoadmapArgs } from "./DeleteRoadmapArgs";
import { RoadmapService } from "../roadmap.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Roadmap)
export class RoadmapResolverBase {
  constructor(
    protected readonly service: RoadmapService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Roadmap",
    action: "read",
    possession: "any",
  })
  async _roadmapsMeta(
    @graphql.Args() args: RoadmapCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Roadmap])
  @nestAccessControl.UseRoles({
    resource: "Roadmap",
    action: "read",
    possession: "any",
  })
  async roadmaps(
    @graphql.Args() args: RoadmapFindManyArgs
  ): Promise<Roadmap[]> {
    return this.service.roadmaps(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Roadmap, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Roadmap",
    action: "read",
    possession: "own",
  })
  async roadmap(
    @graphql.Args() args: RoadmapFindUniqueArgs
  ): Promise<Roadmap | null> {
    const result = await this.service.roadmap(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Roadmap)
  @nestAccessControl.UseRoles({
    resource: "Roadmap",
    action: "delete",
    possession: "any",
  })
  async deleteRoadmap(
    @graphql.Args() args: DeleteRoadmapArgs
  ): Promise<Roadmap | null> {
    try {
      return await this.service.deleteRoadmap(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
